select*
from dbo.sales




select*
from dbo.sales
where Sales_Amount is null 

-- creating copy of sales table 

select* into dbo.sales_copy 
from dbo.sales


select*
from dbo.sales_copy 


-- Cleaning the data in sales_copy table to make it ready for analysis.

-- cleaning the null values and wrong data in Sales_Amount column from sales_copy table (Sales amount is the Revenue so we need to calculate Qty* unit price)

update dbo.sales_copy
set revenue = quantity_sold* price
where revenue is null or revenue = 0   -- This query will update the Sales_Amount column in the sales_copy table by calculating the revenue as the product of quantity and price for any records where Sales_Amount is null or zero. 

-- checking the date column which is varchar(50) we need to convert it into date format   using try_convert function to avoid any conversion error due to wrong date format 

select sales_date ,TRY_CONVERT(date,sales_date) as Converted_SDate
from dbo.sales_copy; 

update dbo.sales_copy 
set sales_date = TRY_CONVERT(date,sales_date) 


alter table dbo.sales_copy
alter column  sales_date date;


select* 
from dbo.sales_copy  -- Date was converted successfully and null values in Sales_Amount column were updated with correct values by multiplying Qty and Price columns. 



-- checking for any duplicate records in sales_copy table 
with dublicates as (
select sales_date, distributer_name, product_name, area_manager, medical_rep, district_manager, line_name, revenue, quantity_sold, zone_name, price,
ROW_NUMBER() over(partition by sales_date, CAST(distributer_name AS NVARCHAR(MAX)),
                CAST(product_name AS NVARCHAR(MAX)),
                CAST(area_manager AS NVARCHAR(MAX)),
                CAST(medical_rep AS NVARCHAR(MAX)),
                CAST(district_manager AS NVARCHAR(MAX)),
                CAST(line_name AS NVARCHAR(MAX)),
                revenue,
                quantity_sold,
                CAST(zone_name AS NVARCHAR(MAX)),
                price order by (revenue)) as rn
from dbo.sales_copy 
) 

select * 
from dublicates 
where rn > 1                    -- No dublicate records found in sales_copy table. 


-- data validation: we checked that revenue column is not calculated correctly 

update dbo.sales_copy
set revenue = quantity_sold* price   -- revenue column is now corrected 



-- Business questions: 

-- we will create views for  3 different analysis which are distributer analysis, product analysis and sales team analysis.

-- We need to know the effective distributer regarding the revenues (Distributer Analysis)

drop view if exists vw_distributer_analysis;

create view vw_distributer_analysis as 
select sales_date , distributer_name , quantity_sold , revenue
from dbo.sales_copy










-- which product we sell alot and which product is generating more revenue over the years and we can focus on those products to increase our sales and revenue and determine seasonal trends.
-- (Product Analysis)

drop view if exists vw_product_analysis;
create view vw_product_analysis as
select sales_date ,  product_name, quantity_sold , revenue
from dbo.sales_copy 



-- Sales team analysis: We will analyze the performance of our sales team by looking at the revenue generated by each area manager, medical reps, and district manager. 
-- This will help us identify top performers and areas for improvement in our sales team.

drop view if exists vw_teams_performance;
create view vw_teams_performance as 
select area_manager ,district_manager , medical_rep,zone_name ,sales_date ,quantity_sold , revenue
from dbo.sales_copy




-- Adhoc analysis for Alexandria Region: 

-- gathering all alexandria region sales data to analyze the performance of this region and identify any specific trends or patterns in sales for this area.
   
-- we need to convert the zone_name column to varchar(max) to avoid any conversion error due to the presence of text data in the zone_name. 
ALTER TABLE dbo.sales_copy 
ALTER COLUMN zone_name varchar(max);

-- Analyze Alexandria sales with running totals per zone
SELECT 
    CAST(distributer_name AS varchar(max)) AS distributer_name,
    CAST(zone_name AS varchar(max)) AS zone_name,
    revenue,
    quantity_sold,
    SUM(revenue) OVER (PARTITION BY CAST(zone_name AS varchar(max))) AS zone_total_revenue,
    SUM(quantity_sold) OVER (PARTITION BY CAST(zone_name AS varchar(max))) AS zone_total_quantity
FROM dbo.sales_copy
WHERE zone_name LIKE '%Alex%' 
   OR zone_name LIKE '%sem%' 
   OR zone_name LIKE '%Mohar%'
ORDER BY zone_total_revenue desc
 -- This query will help us analyze the sales performance of the Alexandria region by summing up the total revenue and quantity sold for that specific region, allowing us to identify any trends or patterns in sales for that area.






